### ISSUE TITLE
NPM tarball is missing javascript files

### ISSUE THREAD

**Issue by gschmottlach** [audio-lab/buffer#2]
I think your NPM tarball (https://registry.npmjs.org/audio-buffer/-/audio-buffer-2.4.1.tgz) is missing a few critical items. I tried to install the following:

npm install audio-buffer -S

then looked in the node_modules/audio-buffer directory and it only contained the following files:

package.json
readme.md

I assume this was not your intention. Could you please update this tarball to include your library components?

Thanks . . .

**Comment by dy** [comment]
Should work now. That was the issue of node6, which failed with graceful-fs and in result instead of whitelisting `"files"` ignored all of them.
Republished, should work.

**Comment by dy** [comment]
I’ve tested, it works, so I close the issue. If you find it broken - just write about it.
Thanks for the report.

**Comment by gschmottlach** [comment]
Thanks for fixing this so quickly . . .
