### ISSUE TITLE
Hey, awesome work here!

### ISSUE THREAD

**Issue by jamen** [audio-lab/buffer#3]
Hi there, and thanks for the invite!  I seen the work here previously, and it is amazing. Glad it is in interest to collaborate with each other.  Speaking of which, is there a place to chat somewhere?  Could not find slack/gitter links at least.

**Comment by dy** [comment]
Ah, guess I should create gitter for that.
For now some ideas/issues/topics can be placed to https://github.com/audio-lab/contributing/issues, but gitter is a good idea too.
I saw your [audiojs](https://github.com/audiojs/audio), and that is very nice you use streams for audio!
There is also very nice [livejs](https://github.com/livejs) organization with streams for audio, but it feels a bit abandoned.

I hope we can try to come to some common format for audio-streams, esp. in node, as it is quite diverse for now. I orient on [node-speaker](https://github.com/tootallnate/node-speaker), and here are [pcm-utils](https://github.com/audio-lab/pcm-util), [audio-through](https://github.com/audio-lab/audio-through) and [audio-speaker](https://github.com/audio-lab/audio-speaker) to ease work with streams.

Now I am working on [web-audio-stream](https://github.com/audio-lab/web-audio-stream) to make it readable.

In plans - releasing audio-spectrum, audio-spectrogram, audio-waveform as a stream analyzer components.

So you’re welcome to use any of these libs or integrate with audiojs in any way.

**Comment by jamen** [comment]
Alright.  I will open up any questions I have there.
